- title: "AWS ONLINE TALKS: Uninterrupted Business"
  desc: |
    Cloud security at AWS is the highest priority. As an AWS customer, you will benefit from a data center and network architecture built to meet the requirements of the most security-sensitive organisations.
    An advantage of the AWS cloud is that it allows customers to scale and innovate, while maintaining a secure environment. Customers pay only for the services they use, meaning that you can have the security you need, but without the upfront expenses, and at a lower cost than in an on-premises environment.

    Register to attend our weekly online talks to explore cloud security and compliance topics and get your questions answered during live Q&A.
  startDate: 2017-4-12
  endDate: 2017-6-6
  link: https://aws.amazon.com/events/security-webinars/
  tags: [online, webinar, free]
- title: PHP[TEK] 2017
  desc: ...the premier PHP conference and annual homecoming for the PHP Community
  startDate: 2017-5-24
  endDate: 2017-5-26
  link: https://tek.phparch.com/
  where: Atlanta
  tags: [in-person, conference]
  registerInfo: Early Bird Ticket sale runs through February 18th, 2017
- title: Arduino workshop
  desc: Arduino? What is that?! Learn the basics of this fun open-source electronic platform. Come explore with us!
  startDate: 2017-6-24
  endDate: 2017-6-24
  link: https://campscui.active.com/orgs/ARHub#/selectSessions/1923602
  where: The Arkansas Regional Innovation Hub
  tags: [in-person, training]
- title: Microsoft Inspire 2017 (Partner conference)
  desc: Microsoft Inspire is where the world meets to transform business. Hear the latest revelations from industry experts, top Microsoft leaders, and fellow Microsoft partners and take part in the face-to-face conversations that can lead to your company’s next big opportunity.
  startDate: 2017-7-9
  endDate: 2017-7-13
  link: https://partner.microsoft.com/en-US/inspire/
  where: DC
  tags: [in-person, conference]
- title: AWS Summit - Chicago
  desc: |
    The AWS Summit brings together the cloud computing community to connect, collaborate and learn about AWS.

    Whether you are new to the cloud or an experienced user, you will learn something new at the AWS Summit. This free event is designed to educate you about the AWS platform. Develop the skills to design, deploy, and operate infrastructure and applications.
  startDate: 2017-7-26
  endDate: 2017-7-27
  link: https://aws.amazon.com/summits/chicago/?refid=ep
  tags: [in-person, conference, free]
- title: Rasberry Pi workshop
  desc: Learn how to set up a Raspberry Pi! This class is perfect for beginners- especially those that own a pi and do not know how to use it!
  startDate: 2017-7-29
  endDate: 2017-7-29
  link: https://campscui.active.com/orgs/ARHub#/selectSessions/1923602
  where: The Arkansas Regional Innovation Hub
  tags: [in-person, training]
- title: VMworld 2017
  desc: |
    VMworld is VMware’s premier thought leadership and education destination for cloud infrastructure and digital workspace technology professionals. Join us for five days of innovation and learn new skills, hear expert insights and gain the tools to enable business success.
  
    At VMworld, you’ll join the industry’s top thought leaders, subject matter experts and IT professionals to immerse yourself in the latest in cloud infrastructure and business mobility technology. 
  
    This is the one indispensable event to discover the technology, trends and people who are shaping the future of digital business.
  startDate: 2017-8-27
  endDate: 2017-8-31
  link: https://www.vmworld.com/en/us/index.html
  where: Las Vegas
  tags: [in-person, conference]
- title: Hacktoberfest 2017
  desc: |
    Support open source and earn a limited edition T-shirt.
    Hacktoberfest is a month-long celebration of open source software in partnership with Github.
  startDate: 2017-10-01
  endDate: 2017-10-31
  link: https://hacktoberfest.digitalocean.com/
  tags: [online, hackathon]
- title: 2017 Northwest Arkansas Technology Summit
  desc: |
    Northwest Arkansas Premier Technology and Innovation Summit. The NWA Technology Summit brings cutting-edge innovation to the latest thinking at the intersection of business and technology.  Want to explore how to innovate and use technology to succeed in the digital era?  Then the Summit is for you. Forward-thinking and practitioner-driven general session speakers and high value breakout sessions will deliver ways that you can effectively collaborate on innovative solutions to common business challenges and learn how technology is powering change and leveling the playing field. 
  startDate: 2017-10-17
  endDate: 2017-10-17
  link: http://www.nwatechsummit.com/
  where: Bentonville, AR
  tags: [in-person, conference]
  twitter: '@NWATech'
- title: DEVIntersection Fall 2017
  desc: |
    In today’s fast-paced world with technology changing rapidly, it’s a challenge to stay on top of everything new while mastering the fundamentals. This exciting event, now in it’s forth year, brings your favorite Microsoft leaders, engineers and industry experts together to educate, network, and share their expertise with you. Just this year, ASP.NET Core, SQL Server 2016, Visual Studio 2015, Windows 10 and SharePoint 2016 launched. The new release of Windows Server is on the horizon and open source is becoming the norm. The cloud is real and so is cloud scaling. Are you ready? Invest in your companies success – and in your career – at an event where questions are answered, strategies are defined and relationships are built.
  startDate: 2017-10-30
  endDate: 2017-11-2
  link: https://www.spintersection.com/#!/Fall-2017
  where: Las Vegas, NV
  tags: [in-person, conference]
- title: PASS Summit 2017
  desc: |
    PASS Summit connects you with industry experts and global data professionals in a unique learning environment that empowers you with the practical knowledge you need to excel in your career.
  startDate: 2017-10-31
  endDate: 2017-11-3
  link: http://www.pass.org/summit/2017/Home.aspx
  where: Seattle, WA
  tags: [in-person, conference]
- title: DeveloperWeek 2018
  desc: |
    Join 8,000 attendees at one of San Francisco’s largest technology-neutral programming conferences & expos. See the full agenda of talks. Join us for the Expo Block party.
  startDate: 2018-2-03
  endDate: 2018-2-08
  link: http://www.developerweek.com//
  where: San Francisco
  tags: [in-person, conference]
- title: Microsoft Tech Summit
  desc: "Build your enterprise or government cloud and infrastructure skills with a two-day free technical training event"
  startDate: 2018-03-5
  endDate: 2018-03-6
  tags: [in-person, conference, free]
  where: "Washington DC"
  link: "https://www.microsoft.com/en-us/techsummit/washington-dc.aspx"
- title: Visual Studio Live! 2018
  desc: |
    During this intense, hard-hitting week of education on the Microsoft Platform, we’ll help you sharpen your skills in Visual Studio, ASP.NET, .NET Core, JavaScript, Xamarin, Database Analytics, and so much more.
  startDate: 2018-03-10
  endDate: 2018-03-16
  link: https://vslive.com/Events/Las-Vegas-2018/Home.aspx
  tags: [in-person, conference]
  where: Las Vegas
  twitter: "#VSLIVE25"
- title: Nowhere Developers Conference
  desc: |
    It’s a conference and event series for developers and engineers, focused on the latest developments in software engineering, machine learning, blockchain, distributed systems, and frontend and backend development.
  startDate: 2018-03-15
  endDate: 2018-03-15
  link: https://www.nowheredevelopers.com/
  where: Bentonville, AR
  tags: [in-person, conference]
  twitter: '@NowhereDev'
- title: Code Stock
  desc: |
    CodeStock is a two day event for technology and information exchange. Created by the community, for the community – this is not an industry trade show pushing the latest in marketing as technology, but a gathering of working professionals sharing knowledge and experience.
  startDate: 2018-04-20
  endDate: 2018-04-21
  link: http://codestock.org/about-conference/
  where: Nashville, TN
  tags: [in-person, conference]
  twitter: '@CodeStock'
- title: Microsoft Build 2018
  desc: Software continues to transform the world in remarkable ways and developers are at the center of it. At Microsoft Build we invite you to join us in downtown Seattle to learn about latest new technologies and exciting plans on the horizon.
  startDate: 2018-05-07
  endDate: 2018-05-09
  link: https://build.microsoft.com/
  where: Seattle, WA
  tags: [in-person, conference]
- title: Google IO 2018
  startDate: 2018-05-08
  endDate: 2018-05-10
  link: https://events.google.com/io/
  where: Shoreline Amphitheatre, Mountain View, CA
  tags: [in-person, conference]
  twitter: '#io18'
- title: NWA TechFest
  desc: |
    NWA TechFest is a technology conference that brings together the tech community to learn from and interact with one another, as well as promoting gender diversity in STEM, economic development opportunities for corporations, and education programs for students and teachers. Proceeds from this conference go to assist STEM-related initiatives in the Northwest Arkansas community.

    With 15 breakout sessions, 2 Keynote speakers, and breakfast and lunch provided, this event is well worth the cost! Network with fellow developers and doers in the Northwest Arkansas community and beyond.
  startDate: 2018-05-17
  endDate: 2018-05-17
  link: https://nwatechfest.com/
  where: Fayetteville, AR
  tags: [in-person, conference]
  twitter: '@NWATechFest'
- title: Music City Code 2018
  desc: Music City Code conference strives to inspire progress in the technology community through education, professional development & thought leadership.
  startDate: 2018-05-31
  endDate: 2018-06-01
  link: https://www.facebook.com/MusicCityCode/
  where: Nashville
  tags: [in-person, conference]
- title: Visual Studio Live! 2018
  desc: Code with industry experts and Microsoft insiders while developing perspective on the Microsoft platform. 
  startDate: 2018-06-10
  endDate: 2018-06-14
  link: https://vslive.com/Events/boston-2018/Home.aspx
  tags: [in-person, conference]
  where: Boston
  twitter: "#VSLIVE25"
- title: DockerCon 2018
  desc: DockerCon is the community and container industry conference for makers and operators of next generation distributed apps built with containers. The three-day conference provides talks by practitioners, hands-on labs, an expo hall of Docker ecosystem innovators and great opportunities to share your experiences with other virtual container enthusiasts.
  startDate: 2018-06-12
  endDate: 2018-06-14
  link: http://2018.dockercon.com/
  tags: [in-person, conference]
  where: San Franciso
- title: KCDC 2018
  desc: |
    The Kansas City Developer Conference is a two-day, multi-track event covering all aspects of software development, design, and project management. We welcome speakers from all over the world who are industry experts that deliver breakout sessions and hands-on workshops to further our attendees’ knowledge and professional skills.
  startDate: 2018-07-12
  endDate: 2018-07-12
  link: http://www.kcdc.info/
  where: Kansas City, MO
  tags: [in-person, conference]
  twitter: '@kc_dc'
- title: Tulsa TechFest 2018
  desc: Two days of learning and sessions
  startDate: 2018-07-20
  endDate: 2018-07-20
  link: http://techfests.com/Tulsa/2018/default.aspx
  twitter: '@TulsaTechFest'
  where: Tulsa, OK
  tags: [in-person, conference]
- title: CoderCruise
  desc: |
    Tired of the usual web technology conference scene? Want a more inclusive experience that lets you get to know your fellow attendees and make connections? Well, CoderCruise was designed to be just this. It's a polyglot developer conference on a cruise ship! This year we will be taking a 5-day, 4-night cruise out of Ft. Lauderdale, FL that includes stops at Half Moon Cay and Nassau.
  startDate: 2018-08-30
  endDate: 2018-09-03
  link: https://www.codercruise.com/
  where: Sail from New Orleans
  tags: [in-person, conference]
- title: .Net Conf
  desc: |
    .NET Conf is a free, 3 day virtual developer event co-organized by the .NET community and Microsoft. Over the course of the three days developers have a wide selection of live sessions that feature speakers from the community and .NET product teams. These are the experts in their field and it is a chance to learn, ask questions live, and get inspired for their next software project.
    
    Developers will learn to build for web, mobile, desktop, games, services, libraries and more for a variety of platforms and devices all with .NET. We’ll have presentations on .NET Core and ASP.NET Core, C#, F#, Roslyn, Visual Studio, Xamarin, and much more.
  startDate: 2018-9-12
  endDate: 2018-9-14
  link: http://www.dotnetconf.net/
  tags: [virtual, conference, free]
- title: Microsoft Ignite
  desc: |
    Microsoft Ignite gives you five days of hands-on learning, industry insights, and direct access to product experts—all in one place. 
    
    700+ sessions
    Interactive Digital Labs
    Direct access to product experts
    Deep dives and demos
    300+ partners at the expo
    Product roadmaps, vision, and strategies
  startDate: 2018-09-24
  endDate: 2018-09-28
  link: https://ignite.microsoft.com/
  where: Orlando, FL
  tags: [in-person, conference]
- title: Strange Loop
  desc: |
    Strange Loop is a multi-disciplinary conference that brings together the developers and thinkers building tomorrow's technology in fields such as emerging languages, alternative databases, concurrency, distributed systems, security, and the web.
  startDate: 2018-09-26
  endDate: 2018-09-28
  link: https://thestrangeloop.com/
  where: St Louis, MO
  tags: [in-person, conference]
- title: Little Rock Tech Fest
  desc: |
    Little Rock Tech Fest is an annual developer conference featuring popular web, mobile, database, devops and related developer topics from industry leaders. It is the event in Little Rock for both professional and aspiring software developers. Speakers from across the country come to present. Students and professionals from across Arkansas and surrounding regions come to learn and network with peers.
    
    Our purpose is to encourage local professionals to increase their skills and to promote the Little Rock region to both experienced and aspiring developers and students.
    
    This is our fifth year hosting the event. Will you join us?
  startDate: 2018-10-04
  endDate: 2018-10-05
  link: http://www.lrtechfest.com/
  where: Little Rock, AR
  tags: [in-person, conference]  
- title: Dev Up
  desc: |
    ST. LOUIS DEVELOPER CONFERENCE
    A THREE DAY EVENT FILLED WITH
    KNOWLEDGE & NETWORKING OPPORTUNITIES
  startDate: 2018-10-08
  endDate: 2018-10-10
  link: http://devupconf.org/
  twitter: '#devup2018'
  where: St Louis, MO
  tags: [in-person, conference]  
- title: IT/Dev Connections 2018
  desc: Professional and uniquely personal, enjoy 3 days of deep-dive technical education!
  startDate: 2018-10-15
  endDate: 2018-10-18
  link: http://www.itdevconnections.com/dc18/Public/Enter.aspx
  where: Dallas
  tags: [in-person, conference]